config/routes.rb
Rails.application.routes.draw do
  resources :climbsites
  root 'climbsites#index'

end

app/models/climbsite.rb
class Climbsite < ActiveRecord::Base
  validates :name, presence: true
  validates :location, presence: true
  validates :grades, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/climbsites_controller.rb
class ClimbsitesController < ApplicationController
  def new
    @climbsite = Climbsite.new
  end

  def create
    @climbsite = Climbsite.new(climbsite_params)
    if @climbsite.save
      redirect_to @climbsite, notice: "Sucessfully created Climbing Site"
    else
      render 'new'
    end
  end

  def show
    @climbsite = Climbsite.find(params[:id])
  end

  def index
    @climbsite = Climbsite.all
  end

  def edit
    @climbsite = Climbsite.edit(params[:id])
  end

  private


  def climbsite_params
    params.require(:climbsite).permit(:name, :location, :grades, :description, :gym)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/climbsites_helper.rb
module ClimbsitesHelper
end

app/views/climbsites/index.html.erb
<div>
  <h1>ClimbingBuddies</h1>
  <h2>Find your future climbing friends</h2>
</div>

<div class='col-lg-6'>
  <div class="col-lg-6">
    <div class="input-group">
      <input type="text" class="form-control">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">Go!</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div>

<% @climbsite.each do |site| %>
  <div class='col-lg-3'>
    <a href="https://placekitten.com/200/300">
    <p><%= link_to site.name, climbsite_path(site)%></p>
    <p>Location: <%= site.location %></p>
  </div>
<% end %>

<div>All rights reserved. 2014</div>

app/views/climbsites/new.html.erb
<h1>Add a new climbing site!</h1>

<%= simple_form_for @climbsite do |f| %>
  <a href="https://placekitten.com/200/300">
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :grades %>
  <%= f.input :description %>
  <%= f.input :gym, as: :boolean, boolean_style: :inline %>

  <%= f.button :submit %>
<%end%>

app/views/climbsites/show.html.erb
<div><h1><%= @climbsite.name %></h1></div>

<a href="http://placekitten.com/200/300">

<div>Location:<h2><%= @climbsite.location %></h2></div>

<div><p><%= @climbsite.description %></p>
<p>Includes grades <%= @climbsite.grades %></p></div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= favicon_link_tag 'favicon.ico' %>

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>

    <%= yield %>
  </body>
</html>